# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iUucVWuifTpT-bwfkax4kmsklt3Bx67y
"""

import numpy as np
import pandas as pd

df=pd.read_csv('/content/placement.csv')

df.head()

#There is an unnecessary column in our dataset so we will remove it

df=df.iloc[:,1:]

df.head()

import matplotlib.pyplot as plt

plt.scatter(df['cgpa'],df['iq'],c=df['placement'])

# Now we will split our independent and dependent variable
X=df.iloc[:,0:2]
Y=df.iloc[:,-1]

X

Y

"""# We are scaling our dataset here

"""

from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.1)

from sklearn.preprocessing import StandardScaler
sc=StandardScaler()

X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

X_train

X_test

"""# We will import our model here , we are going to use Logistic regression model here

"""

from sklearn.linear_model import LogisticRegression

model=LogisticRegression()

#model training
model.fit(X_train,Y_train)

#predicting the values after training my model
y_pred=model.predict(X_test)

from sklearn.metrics import accuracy_score

accuracy_score(Y_test,y_pred)

# we will see how the model basically differntitate
from mlxtend.plotting import plot_decision_regions

plot_decision_regions(X=X_train,y=Y_train.values,clf=model,legend=2)

